# frozen_string_literal: true

source "https://rubygems.org"

# gem "rails"

# gem "jekyll", "~> 4.3"

gem "github-pages", "~> 228", group: :jekyll_plugins

# If you have any plugins, put them here!
group :jekyll_plugins do
    gem "jekyll-feed", "~> 0.12"
    gem 'jekyll-toc'    
end

gem "webrick", "~> 1.8"